build:
  project: '@project.artifactId@'
  timestamp: '@timestamp@'
  version: '@project.version@'

keystone:
  url: ${KEYSTONE_URL:http://127.0.0.1:5000/v3}
  domain: ${KEYSTONE_DOMAIN_CONTEXT:default}

pepe:
  logging:
    tags: ${LOGGING_TAGS:default}
  security:
    disabled: ${SECURITY_DISABLE:false}
  event:
    ttl: ${EVENT_TTL:10000}
  stackstorm:
    api: ${STACKSTORM_URL:http://127.0.0.0:9101/api/v1}
    auth: ${STACKSTORM_URL:http://127.0.0.0:9101/auth/v1}
    stream: ${STACKSTORM_URL:http://127.0.0.0:9101/stream/v1}
    key: ${STACKSTORM_KEY:NOT_KEY}

amqp:
  url: ${RABBIT_URL:amqp://guest:guest@127.0.0.1}
  management:
    url: ${RABBIT_MANAGEMENT_URL:http://127.0.0.1:15672/api}
    login: ${RABBIT_MANAGEMENT_LOGIN:guest}
    password: ${RABBIT_MANAGEMENT_PASSWORD:guest}

spring:
  cache:
    cache-names: userids
    caffeine:
      spec: maximumSize=500, expireAfterAccess=60s
  pid:
    file: ${PID_FILE:/tmp/pepe-api.pid}

server:
  port: ${PORT:8000}
