build:
  project: '@project.artifactId@'
  timestamp: '@timestamp@'
  version: '@project.version@'

keystone:
  url: ${KEYSTONE_URL:http://127.0.0.1:5000/v3}
  domain: ${KEYSTONE_DOMAIN_CONTEXT:default}

pepe:
  logging:
    tags: ${LOGGING_TAGS:default}
  security:
    disabled: ${SECURITY_DISABLE:false}
  event:
    ttl: ${EVENT_TTL:10000}
  stackstorm:
    api: ${STACKSTORM_API_URL:http://127.0.0.0:9101/api/v1}
    auth: ${STACKSTORM_AUTH_URL:http://127.0.0.0:9100/auth/v1}
  cors:
    origins: ${PEPE_CORS_ORIGINS:*}
    methods: ${PEPE_CORS_METHODS:GET,POST,DELETE,PATCH,PUT,HEAD,OPTIONS,TRACE,CONNECT}
  secret: ${PEPE_SECRET:mysecret}

amqp:
  url: ${RABBIT_URL:amqp://guest:guest@127.0.0.1}
  management:
    url: ${RABBIT_MANAGEMENT_URL:http://127.0.0.1:15672/api}
    login: ${RABBIT_MANAGEMENT_LOGIN:guest}
    password: ${RABBIT_MANAGEMENT_PASSWORD:guest}

spring:
  data:
    rest:
      basePath: ${PEPE_MUNIN_API_BASE:/munin/v1}
  datasource:
    driver-class-name: ${DB_API_DRIVER:org.h2.Driver}
    url: ${DB_API_URL:jdbc:h2:mem:test;MODE=MySQL}
    username: ${DB_API_USER:sa}
    password: ${DB_API_PASSWORD:}
  jpa:
    show-sql: ${DB_API_SHOWSQL:false}
    hibernate:
      ddl-auto: ${DB_API_DDL:create}
    properties:
      hibernate:
        dialect: ${DB_API_DIALECT:org.hibernate.dialect.H2Dialect}
  cache:
    cache-names: userids
    caffeine:
      spec: maximumSize=500, expireAfterAccess=60s
  pid:
    file: ${PID_FILE:/tmp/pepe-api.pid}

server:
  port: ${SERVER_PORT:8000}

logbook:
  include:
    - /**
  exclude:
    - /actuator/health
    - /health
    - /info
  filter:
    enabled: true
  format:
    style: json
  obfuscate:
    headers:
      - Authorization
      - X-Auth-Token
  write:
    chunk-size: 1000
    level: info